export const DEFAULT_ITEMS = [
  {
    id: "001",
    img: "public/poloTshirt.png",
    name: "Men's Polo Tshirts",
    price: 249,
    rating: "3.8",
    reviews: "21838 Reviews",
  },
  {
    id: "002",
    img: "public/mensJeans.png",
    name: "Men Regular Jeans",
    price: 372,
    rating: "3.9",
    reviews: "47872 Reviews",
  },
  {
    id: "003",
    img: "public/womenKurti.png",
    name: "Kurtis For Women",
    price: 268,
    rating: "3.8",
    reviews: "87630 Reviews",
  },
  {
    id: "004",
    img: "public/watch.png",
    name: "Stylish Men Watch",
    price: 227,
    rating: "4.0",
    reviews: "845 Reviews",
  },
  {
    id: "005",
    img: "public/shoe.png",
    name: "Modern Men Shoe",
    price: 499,
    rating: "4.2",
    reviews: "10254 Reviews",
  },
  {
    id: "006",
    img: "public/womenBag.png",
    name: "Trendy Women Bag",
    price: 398,
    rating: "3.5",
    reviews: "8945 Reviews",
  },
  {
    id: "007",
    img: "public/sunglass.png",
    name: "Women Round Glasses",
    price: 550,
    rating: "3.9",
    reviews: "5012 Reviews",
  },
  {
    id: "008",
    img: "public/cottonTshirt.png",
    name: "Men's Pure Cotton Tshirt",
    price: 598,
    rating: "4.4",
    reviews: "34500 Reviews",
  },
];
